### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by WarnDa** [Mrredstone5230/SilkTouchAmethyst#1]
Hello,

If there is a budding amethyst that player can't break (example worldguard, or superiorskyblock), if he tries to break it, it will drop on the floor but also keep the amethyst on this place as player can't break it, so it duplicate them !

**Comment by SB2DD** [comment]
I will try to look into this.

**Comment by SB2DD** [comment]
Would this work?

[https://drive.google.com/file/d/1vtdtC7upHiuDu9sqAdqE9XQOFW75atMD/view?usp=sharing](https://drive.google.com/file/d/1vtdtC7upHiuDu9sqAdqE9XQOFW75atMD/view?usp=sharing)

**Comment by WarnDa** [comment]
Hello,
I still get the issue where it duplicate the block, it doesn't break it but it drops one

**Comment by SB2DD** [comment]
I'm deeply sorry for this VERY late answer, but would this work?

https://drive.google.com/file/d/1Am_VReek6BFv_zgClnqi2pyoHqZl6NTS/view?usp=sharing

**Comment by WarnDa** [comment]
Sorry I haven't seen the message before :o
will test it, thanks

**Comment by WarnDa** [comment]
There is still the issue :(
maybe add debug

**Comment by SB2DD** [comment]
Fixed with v1.2
