### ISSUE TITLE
File Size Optimization & Feature Request

### ISSUE THREAD

**Issue by shortybsd** [Mrredstone5230/SilkTouchAmethyst#3]
First off, great plugin! You can clean up the build to not include the following folders/dirs:
Class50
com\zwitserloot
lombok
org

Doing so goes from 1.9mb down to 41kb. :)

Also feature request: Could you add an if check as well as config option to warn or block break event if using a non silk pick? Example: Make it cancel event and display message something like "You need silk touch" and not break the budding amethyst for people that accidently kill them.

**Comment by SB2DD** [comment]
Welp, I finally got time to work on it. Thank you so much for these suggestions, as they've been implemented in the version 1.3 of the plugin. Thank you so much! (and sorry for the wait 😅)

**Comment by shortybsd** [comment]
Thank you so much! Much love!
